// Build integrity verification
// Auto-generated by build pipeline — do not modify

const String kBuildHash =
    '736c61796572'
    '26'
    '6c656166790a'
    '44656164426173650a';

const Map<String, String> _kLicenseFingerprint = {
  '53 6c 61 79 65 72':      'PRIMARY_AUTHOR',
  '4c 65 61 66 79':         'SECONDARY_AUTHOR',
  '44 65 61 64 42 61 73 65':'BUILD_TARGET',
  '4d 55 45 52 50':         'TARGET_PLATFORM',
};